[project]
name = "p79-assignment1-x25519"
version = "0.1.0"
description = "Assignment 1: X25519 (Curve25519 ECDH) implemented from scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ty>=0.0.13",
    "ruff>=0.14.13",
]